// Thai translations for perk descriptions.
export const thaiDescriptions = {
    "Potions and poisons you make are 20% stronger.": "ยาและยาพิษที่คุณสร้างมีประสิทธิภาพเพิ่มขึ้น 20%",
    "Potions and poisons you make are 40% stronger.": "ยาพิษและยาพิษที่คุณทำจะแข็งแกร่งขึ้น 40%",
    "Potions and poisons you make are 60% stronger.": "ยาพิษและยาพิษที่คุณทำจะแข็งแกร่งขึ้น 60%",
    "Potions and poisons you make are 80% stronger.": "ยาและพิษที่คุณทำจะแข็งแกร่งขึ้น 80%",
    "Potions and poisons you make are 100% stronger.": "ยาและยาพิษที่คุณทำจะแข็งแกร่งขึ้น 100%",
    "Potions you mix that restore Health, Magicka or Stamina are 25% more powerful.": "ยาที่คุณผสมเพื่อฟื้นฟูสุขภาพ Magicka หรือ Stamina จะมีพลังมากขึ้น 25%",
    "Poisons you mix are 25% more effective.": "พิษที่คุณผสมจะมีประสิทธิภาพมากขึ้น 25%",
    "Potions you mix with beneficial effects have an additional 25% greater magnitude.": "ยาที่คุณผสมกับเอฟเฟกต์จะมีพลังเพิ่มขึ้นอีก 25%",
    "Poisins applied to weapons last for twice as many hits.": "ยาพิษที่เคลือบอาวุธจะออกฤทธิ์ได้นานขึ้น 2 เท่า",
    "Eating an ingredient reveals first two effects.": "การรับประทานส่วนผสมจะเผยให้เห็นผลกระทบสองประการแรก",
    "Eating an ingredient reveals first three effects.": "การรับประทานส่วนผสมจะเผยให้เห็นผลกระทบสามประการแรก",
    "Eating an ingredient reveals first four effects.": "การรับประทานส่วนผสมจะเผยให้เห็นผลกระทบสี่ประการแรก",
    "Two ingredients are gathered from plants.": "รวบรวมส่วนผสมสองอย่างจากพืช",
    "50% resistance to all poisons.": "ต้านทานพิษทั้งหมด 50%",
    "All negative effects are removed from created potions, and all positive effects are removed from created poisons.": "ผลกระทบเชิงลบทั้งหมดจะถูกลบออกจากยาที่สร้างขึ้น และผลกระทบเชิงบวกทั้งหมดจะถูกลบออกจากยาพิษที่สร้างขึ้น",
    "Cast Novice level Illusion spells for half magicka.": "ร่ายเวทย์มนตร์ระดับเริ่มต้นใช้เวทมนตร์เพียงครึ่งเดียว",
    "Dual casting an Illusion spell overcharges the effects into an even more powerful version.": "การใช้เวทย์มนตร์ Illusion แบบคู่จะชาร์จเอฟเฟกต์มากเกินไปจนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
    "Cast Apprentice level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
    "Calm spells now work on higher level opponents. Cumulative with Kindred Mage and Animage.": "คาถาสงบตอนนี้ใช้ได้กับคู่ต่อสู้ที่มีเลเวลสูงกว่าแล้ว สะสมด้วย Kindred Mage และ Animage",
    "Illusion spells now work on higher level animals.": "คาถาภาพลวงตาตอนนี้ใช้ได้กับสัตว์ที่มีเลเวลสูงกว่าแล้ว",
    "Cast Adept level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Expert level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Master level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
    "Fear spells work on higher level opponents. Cumulative with Kindred Mage and Animage.": "คาถาความกลัวใช้ได้กับคู่ต่อสู้ที่มีระดับสูงกว่า สะสมด้วย Kindred Mage และ Animage",
    "Frenzy spells work on higher level opponents. Cumulative with Kindred Mage and Animage.": "คาถาบ้าคลั่งใช้ได้กับคู่ต่อสู้ที่มีเลเวลสูงกว่า สะสมด้วย Kindred Mage และ Animage",
    "All Illusion spells work on higher level people.": "คาถาภาพลวงตาทั้งหมดใช้ได้กับผู้คนที่มีระดับสูงกว่า",
    "All spells you cast from any school of magic are silent to others.": "คาถาทั้งหมดที่คุณร่ายจากโรงเรียนเวทมนตร์แห่งใดก็ตามจะไม่ส่งเสียงต่อผู้อื่น",
    "Illusion spells work on undead, daedra and automatons.": "คาถาภาพลวงตาใช้ได้กับอันเดด เดดรา และออโตเมตอน",
    "Cast Novice level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Novice ใช้ Magicka เพียงครึ่งเดียว",
    "Can summon atronachs or raise undead twice as far away.": "สามารถเรียก atronachs หรือปลุก Undead ขึ้นมาสองเท่าในระยะไกล",
    "Can summon atronachs or raise undead three times as far away.": "สามารถเรียก atronachs หรือปลุก Undead ได้สามครั้งในระยะไกล",
    "Dual casting a Conjuration spell overcharges the spell, allowing it to last longer.": "การร่ายเวทย์มนตร์แบบคู่จะชาร์จพลังเวทย์มากเกินไป และทำให้คงอยู่ได้นานขึ้น",
    "Greater duration for reanimated undead.": "ระยะเวลาที่มากขึ้นสำหรับอันเดดที่ฟื้นคืนชีพ",
    "Bound weapons do more damage.": "อาวุธ Bound สร้างความเสียหายเพิ่มขึ้น",
    "Cast Apprentice level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
    "Double duration for conjured Atronachs.": "ระยะเวลาสองเท่าสำหรับ Atronach ที่เสก",
    "Conjured Atronachs are 50% more powerful.": "Atronachs ที่เสกจะมีพลังมากขึ้น 50%",
    "Reanimated undead have 100 points more health.": "Undead ที่ฟื้นคืนชีพจะมีสุขภาพเพิ่มขึ้น 100 แต้ม",
    "You can have two atronachs or reanimated zombies.": "คุณสามารถมี atronach สองตัวหรือซอมบี้ที่ฟื้นคืนชีพได้",
    "Bound weapons cast Soul Trap on targets.": "อาวุธ Bound ร่าย Soul Trap ใส่เป้าหมาย",
    "Bound weapons will banish summoned creatures and turn raised ones.": "อาวุธ Bound จะขับไล่สิ่งมีชีวิตที่ถูกอัญเชิญ และทำให้ Undead ที่ถูกชุบฟื้นหนีไป",
    "Cast Adept level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Expert level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Master level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Novice level Destruction spells for half magicka.": "คาถาทำลายล้างระดับเริ่มต้นใช้เวทมนตร์เพียงครึ่งเดียว",
    "Dual casting a Destruction spell overcharges the effects into an even more powerful version.": "การร่ายเวทย์ทำลายล้างแบบคู่จะอัดพลังเอฟเฟกต์มากเกินไปจนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
    "Most destruction spells will stagger an opponent when dual cast.": "คาถาทำลายล้างส่วนใหญ่จะทำให้คู่ต่อสู้เดินโซเซเมื่อร่ายแบบคู่",
    "Fire spells do 25% more damage.": "เวทย์ไฟสร้างความเสียหายเพิ่มขึ้น 25%",
    "Fire spells do 50% more damage.": "เวทย์ไฟสร้างความเสียหายเพิ่มขึ้น 50%",
    "Fire damage causes targets to flee if their health is low.": "ความเสียหายจากไฟจะทำให้เป้าหมายหลบหนีหากพลังชีวิตต่ำ",
    "Frost spells do 25% more damage.": "คาถาน้ำแข็งสร้างความเสียหายเพิ่มขึ้น 25%",
    "Frost spells do 50% more damage.": "คาถาน้ำแข็งสร้างความเสียหายเพิ่มขึ้น 50%",
    "Frost damage paralyzes targets if their health is low.": "ความเสียหายจากน้ำแข็งจะทำให้เป้าหมายเป็นอัมพาตหากพลังชีวิตของพวกเขาต่ำ",
    "Shock spells do 25% more damage.": "คาถาช็อตสร้างความเสียหายเพิ่มขึ้น 25%",
    "Shock spells do 50% more damage.": "คาถาช็อตสร้างความเสียหายเพิ่มขึ้น 50%",
    "Shock damage disintegrates targets if their health is low.": "ความเสียหายจากช็อตจะสลายเป้าหมายหากพลังชีวิตของพวกเขาต่ำ",
    "Cast Apprentice level Destruction spells for half magicka.": "ร่ายคาถาสายทำลายล้างระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
    "Can place runes five times farther away.": "สามารถวางรูนได้ไกลออกไปห้าเท่า",
    "Cast Adept level Destruction spells for half magicka.": "ร่ายคาถาสายทำลายล้างระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Expert level Destruction spells for half magicka.": "ร่ายคาถาทำลายล้างระดับผู้เชี่ยวชาญใช้เวทมนตร์เพียงครึ่งเดียว",
    "Cast Master level Destruction spells for half magicka.": "คาถาทำลายล้างระดับปรมาจารย์ใช้เวทมนตร์เพียงครึ่งเดียว",
    "Cast Novice level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Novice ใช้ Magicka เพียงครึ่งเดียว",
    "Healing spells also restore Stamina.": "คาถารักษายังช่วยฟื้นฟูความแข็งแกร่งอีกด้วย",
    "Healing spells cure 50% more.": "คาถารักษารักษาได้มากขึ้น 50%",
    "All spells are more effective against undead.": "คาถาทั้งหมดมีประสิทธิภาพมากกว่ากับอันเดด",
    "Wards recharge your magicka when hit with spells.": "วอร์ดจะชาร์จเวทย์มนตร์ของคุณเมื่อถูกโจมตีด้วยคาถา",
    "Cast Apprentice level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Adept level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Expert level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
    "Cast Master level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
    "Magicka regenerates 25% faster.": "Magicka ฟื้นฟูเร็วขึ้น 25%",
    "Magicka regenerates 50% faster.": "Magicka ฟื้นฟูเร็วขึ้น 50%",
    "Once a day, heals 250 points automatically if you fall below 10% health.": "วันละครั้ง จะรักษา 250 แต้มโดยอัตโนมัติหากคุณมีพลังชีวิตต่ำกว่า 10%",
    "Dual casting a Restoration spell overcharges the effects into an even more powerful version.": "การร่ายเวทย์มนตร์การฟื้นฟูแบบคู่จะชาร์จเอฟเฟกต์มากเกินไปจนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
    "Cast Novice level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Novice ใช้ Magicka เพียงครึ่งเดียว",
    "Dual casting an Alteration spell overcharges the effects into an even more powerful version.": "การร่ายเวทย์มนตร์ Alteration แบบคู่จะเพิ่มพลังให้กับเอฟเฟกต์จนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
    "Cast Apprentice level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
    "Protection spells like Stoneflesh are twice as strong if not wearing armor.": "คาถาป้องกันเช่น Stoneflesh จะแข็งแกร่งเป็นสองเท่าหากไม่ได้สวมชุดเกราะ",
    "Protection spells like Stoneflesh are 2.5 times as strong if not wearing armor.": "คาถาป้องกันอย่าง Stoneflesh มีประสิทธิภาพเพิ่มเป็น 2.5 เท่าเมื่อไม่สวมเกราะ",
    "Protection spells like Stoneflesh are three times as strong if not wearing armor.": "คาถาป้องกันอย่าง Stoneflesh มีประสิทธิภาพเพิ่มเป็น 3 เท่าเมื่อไม่สวมเกราะ",
    "Blocks 10% of a spell's effects.": "ต้านทานผลของคาถา 10%",
    "Blocks 20% of a spell's effects.": "ต้านทานผลของคาถา 20%",
    "Blocks 30% of a spell's effects.": "ต้านทานผลของคาถา 30%",
    "Cast Adept level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
    "Alteration spells have 50% greater duration.": "คาถาสาย Alteration มีระยะเวลานานขึ้น 50%",
    "Cast Expert level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
    "Absorb 30% of the magicka of any spells that hit you.": "ดูดซับเวทย์มนตร์ 30% ของคาถาที่โจมตีคุณ",
    "Cast Master level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
    "New enchantments are 20% stronger.": "มนต์เสน่ห์ใหม่แข็งแกร่งขึ้น 20%",
    "New enchantments are 40% stronger.": "มนต์เสน่ห์ใหม่แข็งแกร่งขึ้น 40%",
    "New enchantments are 60% stronger.": "มนต์เสน่ห์ใหม่แข็งแกร่งขึ้น 60%",
    "New enchantments are 80% stronger.": "มนต์เสน่ห์ใหม่แข็งแกร่งขึ้น 80%",
    "New enchantments are 100% stronger.": "มนต์เสน่ห์ใหม่แข็งแกร่งขึ้น 100%",
    "Fire enchantments on weapons and armor are 25% stronger.": "มนต์เสน่ห์ไฟบนอาวุธและชุดเกราะนั้นแข็งแกร่งขึ้น 25%",
    "Skill enchantments on armor are 25% stronger.": "ทักษะการร่ายมนตร์บนชุดเกราะนั้นแข็งแกร่งขึ้น 25%",
    "Soul gems provide extra magicka for recharging.": "Soul gems มอบเวทย์มนตร์พิเศษสำหรับการชาร์จใหม่",
    "Death blows to creatures, but not people, trap 5% of the victim's soul, recharging the weapon.": "การสังหารสิ่งมีชีวิตที่ไม่ใช่มนุษย์มีโอกาส 5% ดักจับวิญญาณของเป้าหมายและชาร์จอาวุธ",
    "Frost enchantments on weapons and armor are 25% stronger.": "มนต์เสน่ห์ฟรอสต์บนอาวุธและชุดเกราะนั้นแข็งแกร่งขึ้น 25%",
    "Shock enchantments on weapons and armor are 25% stronger.": "มนต์เสน่ห์สายสายฟ้าบนอาวุธและชุดเกราะมีประสิทธิภาพเพิ่มขึ้น 25%",
    "Health, magicka, and stamina enchantments on armor are 25% stronger.": "พลังชีวิต เวทมนตร์ และความแข็งแกร่งบนชุดเกราะแข็งแกร่งขึ้น 25%",
    "Can put two enchantments on the same item.": "สามารถใส่มนต์เสน่ห์ได้ 2 อย่างในรายการเดียวกัน",
    "Can create Steel armor and weapons at forges, and improve them twice as much.": "สามารถสร้างเกราะเหล็กและอาวุธที่โรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Can create Elven armor and weapons at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะและอาวุธของเอลฟ์จากโรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "You can improve magical weapons and armor.": "คุณสามารถปรับปรุงอาวุธและชุดเกราะเวทย์มนตร์ได้",
    "Can create Dwarven armor and weapons at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะและอาวุธของคนแคระที่โรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Can create Scaled and Plate armor at forges, and improve them twice as much.": "สามารถสร้างเกราะ Scaled และ Plate ที่โรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Can create Glass armor and weapons at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะแก้วและอาวุธที่โรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Can create Orcish armor and weapons at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะและอาวุธ Orcish ที่โรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Can create Ebony armor and weapons at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะและอาวุธไม้มะเกลือจากโรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Can create Daedric armor and weapons at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะและอาวุธ Daedric จากโรงตีเหล็ก และปรับปรุงได้มากเป็นสองเท่า",
    "Can create Dragon armor at forges, and improve them twice as much.": "สามารถสร้างชุดเกราะมังกรที่โรงตีเหล็ก และปรับปรุงพวกมันได้มากเป็นสองเท่า",
    "Increases armor rating for Heavy Armor by 20%.": "ค่าป้องกันของ Heavy Armor เพิ่มขึ้น 20%",
    "Increases armor rating for Heavy Armor by 40%.": "ค่าป้องกันของ Heavy Armor เพิ่มขึ้น 40%",
    "Increases armor rating for Heavy Armor by 60%.": "ค่าป้องกันของ Heavy Armor เพิ่มขึ้น 60%",
    "Increases armor rating for Heavy Armor by 80%.": "ค่าป้องกันของ Heavy Armor เพิ่มขึ้น 80%",
    "Increases armor rating for Heavy Armor by 100%.": "ค่าป้องกันของ Heavy Armor เพิ่มขึ้น 100%",
    "Unarmed attacks with Heavy Armor gauntlets do their armor rating in extra damage.": "การโจมตีมือเปล่าขณะสวมถุงมือเกราะหนัก สร้างความเสียหายเพิ่มเติมเท่ากับค่าป้องกันของถุงมือ",
    "Half damage from falling if wearing all Heavy Armor: head, chest, hands, feet.": "ได้รับความเสียหายจากการตกจากที่สูงลดลง 50% เมื่อสวม Heavy Armor ครบชุด: ศีรษะ, ลำตัว, มือ และเท้า",
    "Heavy Armor weighs nothing and doesn't slow you down when worn.": "Heavy Armor ไม่มีน้ำหนักและไม่ทำให้คุณช้าลงเมื่อสวมใส่",
    "25% Armor bonus if wearing all Heavy Armor: head, chest, hands, feet.": "โบนัสเกราะ 25% หากสวมเกราะหนักทั้งหมด: หัว, หน้าอก, มือ, เท้า",
    "50% less stagger when wearing only Heavy Armor.": "เดินโซเซน้อยลง 50% เมื่อสวมเฉพาะเกราะหนัก",
    "Additional 25% Armor bonus if wearing a matched set of Heavy Armor.": "โบนัสเกราะเพิ่มเติม 25% หากสวมชุดเกราะหนักที่ตรงกัน",
    "10% chance to reflect melee damage back to the enemy while wearing all Heavy Armor: head, chest, hands, feet.": "มีโอกาส 10% ที่จะสะท้อนความเสียหายระยะประชิดกลับไปยังศัตรูขณะสวมเกราะหนักทั้งหมด: หัว, หน้าอก, มือ, เท้า",
    "Blocking is 20% more effective.": "การบล็อกมีประสิทธิภาพมากขึ้น 20%",
    "Blocking is 25% more effective.": "การบล็อกมีประสิทธิภาพมากขึ้น 25%",
    "Blocking is 30% more effective.": "การบล็อกมีประสิทธิภาพมากขึ้น 30%",
    "Blocking is 35% more effective.": "การบล็อกมีประสิทธิภาพมากขึ้น 35%",
    "Blocking is 40% more effective.": "การบล็อกมีประสิทธิภาพมากขึ้น 40%",
    "Arrows that hit the shield do no damage.": "ลูกศรที่โดนโล่จะไม่สร้างความเสียหาย",
    "Time slows down if you are blocking during an enemy's power attack.": "เวลาจะช้าลงหากคุณกำลังบล็อคในระหว่างการโจมตีด้วยพลังของศัตรู",
    "Able to do a power bash.": "สามารถทำการทุบตีพลังได้",
    "Blocking with a shield reduces incoming fire, frost, and shock damage by 50%.": "การปิดกั้นด้วยโล่จะช่วยลดความเสียหายจากไฟ น้ำค้างแข็ง และแรงกระแทกที่เข้ามา 50%",
    "Able to move faster with a shield raised.": "สามารถเคลื่อนที่ได้เร็วขึ้นด้วยการยกโล่ขึ้น",
    "Bashing does five times more damage.": "การทุบตีจะสร้างความเสียหายได้มากกว่าห้าเท่า",
    "Chance to disarm when power bashing.": "มีโอกาสปลดอาวุธเมื่อถูกโจมตีด้วยพลัง",
    "Sprinting with a shield raised knocks down most targets.": "การวิ่งด้วยโล่ที่ยกขึ้นจะทำให้เป้าหมายส่วนใหญ่ล้มลง",
    "Two-Handed weapons do 20% more damage.": "อาวุธสองมือสร้างความเสียหายเพิ่มขึ้น 20%",
    "Two-Handed weapons do 40% more damage.": "อาวุธสองมือสร้างความเสียหายได้มากขึ้น 40%",
    "Two-Handed weapons do 60% more damage.": "อาวุธสองมือสร้างความเสียหายได้มากขึ้น 60%",
    "Two-Handed weapons do 80% more damage.": "อาวุธสองมือสร้างความเสียหายได้มากขึ้น 80%",
    "Two-Handed weapons do 100% more damage.": "อาวุธสองมือสร้างความเสียหายได้มากขึ้น 100%",
    "Attacks with battle axes cause extra bleeding damage.": "การโจมตีด้วยขวานต่อสู้จะสร้างความเสียหายเลือดออกเป็นพิเศษ",
    "Power attacks with two-handed weapons cost 25% less stamina.": "การโจมตีด้วยพลังด้วยอาวุธสองมือใช้ค่าความแข็งแกร่งลดลง 25%",
    "Attacks with greatsword have a 10% chance of doing critical damage.": "การโจมตีด้วยดาบใหญ่มีโอกาส 10% ที่จะสร้างความเสียหายคริติคอล",
    "Attacks with greatsword have a 15% chance of doing critical damage.": "การโจมตีด้วยดาบใหญ่มีโอกาส 15% ที่จะสร้างความเสียหายคริติคอล",
    "Attacks with greatsword have a 20% chance of doing critical damage.": "การโจมตีด้วยดาบใหญ่มีโอกาส 20% ที่จะสร้างความเสียหายคริติคอล",
    "Attacks with warhammers ignore 25% of armor.": "การโจมตีด้วยค้อนสงครามจะไม่สนใจเกราะ 25%",
    "Attacks with warhammers ignore 50% of armor.": "การโจมตีด้วยค้อนสงครามจะไม่สนใจเกราะ 50%",
    "Attacks with warhammers ignore 75% of armor.": "การโจมตีด้วยค้อนสงครามจะไม่สนใจเกราะ 75%",
    "Can do a two-handed power attack while sprinting that does double critical damage.": "สามารถโจมตีด้วยพลังสองมือขณะวิ่งซึ่งสร้างความเสียหายคริติคอลเป็นสองเท่า",
    "Standing power attacks do 25% bonus damage with a chance to decapitate your enemies.": "การโจมตีด้วยพลังยืนจะสร้างโบนัสความเสียหาย 25% พร้อมโอกาสในการตัดหัวศัตรูของคุณ",
    "Sideways power attacks with two-handed weapons hit all targets in front of you.": "โจมตีด้วยอาวุธสองมือด้านข้างโจมตีทุกเป้าหมายที่อยู่ตรงหน้าคุณ",
    "Backwards power attack has a 25% chance to paralyze the target.": "การโจมตีด้วยพลังถอยหลังมีโอกาส 25% ที่จะทำให้เป้าหมายเป็นอัมพาต",
    "One-Handed weapons do 20% more damage.": "อาวุธมือเดียวสร้างความเสียหายได้มากขึ้น 20%",
    "One-Handed weapons do 40% more damage.": "อาวุธมือเดียวสร้างความเสียหายได้มากขึ้น 40%",
    "One-Handed weapons do 60% more damage.": "อาวุธมือเดียวสร้างความเสียหายได้มากขึ้น 60%",
    "One-Handed weapons do 80% more damage.": "อาวุธมือเดียวสร้างความเสียหายได้มากขึ้น 80%",
    "One-Handed weapons do 100% more damage.": "อาวุธมือเดียวสร้างความเสียหายได้มากขึ้น 100%",
    "Attacks with war axes cause extra bleeding damage.": "การโจมตีด้วยขวานสงครามทำให้เกิดความเสียหายเลือดออกเป็นพิเศษ",
    "Power attacks with one-handed-weapons cost 25% less stamina.": "การโจมตีด้วยพลังด้วยอาวุธมือเดียวจะใช้ค่าความแข็งแกร่งลดลง 25%",
    "Attacks with maces ignore 25% of armor.": "การโจมตีด้วยกระบองจะไม่สนใจเกราะ 25%",
    "Attacks with maces ignore 50% of armor.": "การโจมตีด้วยกระบองจะไม่สนใจเกราะ 50%",
    "Attacks with maces ignore 75% of armor.": "การโจมตีด้วยกระบองจะไม่สนใจเกราะ 75%",
    "Attacks with swords have a 10% chance of doing critical damage.": "การโจมตีด้วยดาบมีโอกาส 10% ที่จะสร้างความเสียหายคริติคอล",
    "Attacks with swords have a 15% chance of doing critical damage.": "การโจมตีด้วยดาบมีโอกาส 15% ที่จะสร้างความเสียหายคริติคอล",
    "Attacks with swords have a 20% chance of doing critical damage.": "การโจมตีด้วยดาบมีโอกาส 20% ที่จะสร้างความเสียหายคริติคอล",
    "Dual wielding attacks are 20% faster.": "การโจมตีด้วยอาวุธคู่เร็วขึ้น 20%",
    "Dual wielding attacks are 35% faster.": "การโจมตีด้วยอาวุธคู่เร็วขึ้น 35%",
    "Dual wielding power attacks do 50% bonus damage.": "การโจมตีด้วยพลังอาวุธคู่จะสร้างความเสียหายโบนัส 50%",
    "Can do a one-handed power attack while sprinting that does double critical damage.": "สามารถโจมตีด้วยพลังด้วยมือเดียวขณะวิ่งซึ่งสร้างความเสียหายคริติคอลเป็นสองเท่า",
    "Bows do 20% more damage.": "ธนูสร้างความเสียหายเพิ่มขึ้น 20%",
    "Bows do 40% more damage.": "ธนูสร้างความเสียหายเพิ่มขึ้น 40%",
    "Bows do 60% more damage.": "ธนูสร้างความเสียหายเพิ่มขึ้น 60%",
    "Bows do 80% more damage.": "ธนูสร้างความเสียหายเพิ่มขึ้น 80%",
    "Bows do 100% more damage.": "ธนูสร้างความเสียหายได้มากขึ้น 100%",
    "Pressing Block while aiming will zoom in your view.": "การกดบล็อกขณะเล็งจะซูมมุมมองของคุณ",
    "10% chance of a critical hit that does extra damage.": "มีโอกาส 10% ที่จะโจมตีคริติคอลที่สร้างความเสียหายเพิ่มเติม",
    "15% chance of a critical hit that does extra damage.": "มีโอกาส 15% ที่จะโจมตีคริติคอลที่สร้างความเสียหายเพิ่มเติม",
    "20% chance of a critical hit that does extra damage.": "มีโอกาส 20% ที่จะโจมตีคริติคอลที่สร้างความเสียหายเพิ่มเติม",
    "Zooming in with a bow slows time by 25%.": "การซูมเข้าด้วยธนูจะทำให้เวลาช้าลง 25%",
    "Zooming in with a bow slows time by 50%.": "การซูมเข้าด้วยธนูจะทำให้เวลาช้าลง 50%",
    "Arrows stagger all but the largest opponents 50% of the time.": "ลูกธนูมีโอกาส 50% ทำให้ศัตรูทุกขนาด ยกเว้นตัวที่ใหญ่ที่สุด เสียหลัก",
    "Can draw a bow 30% faster.": "สามารถชักธนูได้เร็วขึ้น 30%",
    "Recover twice as many arrows from dead bodies.": "กู้คืนลูกธนูจากศพเป็นสองเท่า",
    "Able to move faster with a drawn bow.": "สามารถเคลื่อนที่ได้เร็วขึ้นด้วยธนูที่ชักออกมา",
    "15% chance of paralyzing the target for a few seconds.": "มีโอกาส 15% ที่จะทำให้เป้าหมายเป็นอัมพาตเป็นเวลาไม่กี่วินาที",
    "Increase armor rating for Light armor by 20%.": "ค่าป้องกันของ Light Armor เพิ่มขึ้น 20%",
    "Increase armor rating for Light armor by 40%.": "ค่าป้องกันของ Light Armor เพิ่มขึ้น 40%",
    "Increase armor rating for Light armor by 60%.": "ค่าป้องกันของ Light Armor เพิ่มขึ้น 60%",
    "Increase armor rating for Light armor by 80%.": "ค่าป้องกันของ Light Armor เพิ่มขึ้น 80%",
    "Increase armor rating for Light armor by 100%.": "ค่าป้องกันของ Light Armor เพิ่มขึ้น 100%",
    "25% Armor bonus if wearing all Light Armor: head, chest, hands, feet.": "โบนัสเกราะ 25% หากสวมเกราะเบาทั้งหมด: หัว, หน้าอก, มือ, เท้า",
    "Light Armor weighs nothing and doesn't slow you down when worn.": "Light Armor ไม่มีน้ำหนักและไม่ทำให้คุณช้าลงเมื่อสวมใส่",
    "Additional 25% Armor bonus if wearing a matched set of Light Armor.": "โบนัสเกราะเพิ่มเติม 25% หากสวมชุดเกราะเบาที่ตรงกัน",
    "Stamina regenerates 50% faster in all Light Armor: head, chest, hands, feet.": "ความแข็งแกร่งจะฟื้นฟูเร็วขึ้น 50% ในชุดเกราะเบาทั้งหมด: หัว, หน้าอก, มือ, เท้า",
    "10% chance of avoiding all damage from a melee attack while wearing all Light Armor: head, chest, hands, feet.": "มีโอกาส 10% ที่จะหลีกเลี่ยงความเสียหายทั้งหมดจากการโจมตีระยะประชิดขณะสวมเกราะเบาทั้งหมด: หัว, หน้าอก, มือ, เท้า",
    "You are 20% harder to detect when sneaking.": "ขณะลอบเร้น ศัตรูตรวจพบคุณได้ยากขึ้น 20%",
    "You are 25% harder to detect when sneaking.": "ขณะลอบเร้น ศัตรูตรวจพบคุณได้ยากขึ้น 25%",
    "You are 30% harder to detect when sneaking.": "ขณะลอบเร้น ศัตรูตรวจพบคุณได้ยากขึ้น 30%",
    "You are 35% harder to detect when sneaking.": "ขณะลอบเร้น ศัตรูตรวจพบคุณได้ยากขึ้น 35%",
    "You are 40% harder to detect when sneaking.": "ขณะลอบเร้น ศัตรูตรวจพบคุณได้ยากขึ้น 40%",
    "Sneak attacks with one-handed weapons now do six times damage.": "การแอบโจมตีด้วยอาวุธมือเดียวจะสร้างความเสียหายได้หกเท่า",
    "Sneak attacks with bows now do three times damage.": "การโจมตีแบบลอบโจมตีด้วยธนูจะสร้างความเสียหายได้ 3 เท่า",
    "Sneak attacks with daggers now do a total of fifteen times normal damage.": "การโจมตีด้วยมีดสั้นตอนนี้จะสร้างความเสียหายรวม 15 เท่าของความเสียหายปกติ",
    "Noise from armor is reduced 50%.": "เสียงจากเกราะลดลง 50%",
    "You won't trigger pressure plates.": "คุณจะไม่เรียกใช้แผ่นแรงดัน",
    "Sprinting while sneaking executes a silent forward roll.": "วิ่งขณะลอบเร้นเพื่อกลิ้งตัวไปข้างหน้าอย่างเงียบเชียบ",
    "Walking and running does not affect detection.": "การเดินและวิ่งไม่ส่งผลต่อการตรวจจับ",
    "Crouching stops combat for a moment and forces distant opponents to search for a target.": "การหมอบหยุดการต่อสู้ชั่วขณะและบังคับให้คู่ต่อสู้ที่อยู่ห่างไกลค้นหาเป้าหมาย",
    "Novice locks are much easier to pick.": "สะเดาะกุญแจระดับ Novice ได้ง่ายขึ้นมาก",
    "Apprentice locks are much easier to pick.": "สะเดาะกุญแจระดับ Apprentice ได้ง่ายขึ้นมาก",
    "Able to pick locks without being noticed.": "สะเดาะกุญแจได้โดยไม่ถูกสังเกต",
    "Automatically gives you a copy of a picked lock's key if it has one.": "เมื่อสะเดาะกุญแจสำเร็จ จะได้รับสำเนากุญแจของมันโดยอัตโนมัติหากมี",
    "Adept locks are much easier to pick.": "สะเดาะกุญแจระดับ Adept ได้ง่ายขึ้นมาก",
    "Find more gold in chests.": "ค้นหาทองคำเพิ่มเติมในหีบ",
    "50% greater chance of finding special treasure.": "มีโอกาสมากขึ้น 50% ในการค้นหาสมบัติพิเศษ",
    "Expert locks are much easier to pick.": "สะเดาะกุญแจระดับ Expert ได้ง่ายขึ้นมาก",
    "Pick starts close to the lock opening position.": "เริ่มหมุนสะเดาะกุญแจใกล้ตำแหน่งปลดล็อกมากขึ้น",
    "Lockpicks never break.": "สะเดาะกุญแจไม่หัก",
    "Master locks are much easier to pick.": "สะเดาะกุญแจระดับ Master ได้ง่ายขึ้นมาก",
    "Pickpocketing bonus of 20%. Item weight and value reduce pickpocketing odds.": "โอกาสล้วงกระเป๋าเพิ่มขึ้น 20% น้ำหนักและมูลค่าของไอเทมจะลดโอกาสล้วงกระเป๋า",
    "Pickpocketing bonus of 40%. Item weight and value reduce pickpocketing odds.": "โอกาสล้วงกระเป๋าเพิ่มขึ้น 40% น้ำหนักและมูลค่าของไอเทมจะลดโอกาสล้วงกระเป๋า",
    "Pickpocketing bonus of 60%. Item weight and value reduce pickpocketing odds.": "โอกาสล้วงกระเป๋าเพิ่มขึ้น 60% น้ำหนักและมูลค่าของไอเทมจะลดโอกาสล้วงกระเป๋า",
    "Pickpocketing bonus of 80%. Item weight and value reduce pickpocketing odds.": "โอกาสล้วงกระเป๋าเพิ่มขึ้น 80% น้ำหนักและมูลค่าของไอเทมจะลดโอกาสล้วงกระเป๋า",
    "Pickpocketing bonus of 100%. Item weight and value reduce pickpocketing odds.": "โอกาสล้วงกระเป๋าเพิ่มขึ้น 100% น้ำหนักและมูลค่าของไอเทมจะลดโอกาสล้วงกระเป๋า",
    "+25% chance to pickpocket if the target is asleep.": "มีโอกาสล้วงกระเป๋า +25% หากเป้าหมายหลับอยู่",
    "Silently harm enemies by placing poisons in their pockets.": "ทำร้ายศัตรูอย่างเงียบๆ โดยการวางยาพิษไว้ในกระเป๋าของพวกมัน",
    "Pickpocketing gold is 50% easier.": "ล้วงกระเป๋าเหรียญทองได้ง่ายขึ้น 50%",
    "Carrying capacity is increased by 100.": "ความสามารถในการบรรทุกเพิ่มขึ้น 100",
    "Pickpocketing keys almost always works.": "ล้วงกระเป๋าเอากุญแจสำเร็จเกือบทุกครั้ง",
    "Can pickpocket equipped weapons.": "สามารถล้วงกระเป๋าอาวุธที่ติดตั้งได้",
    "Can pickpocket equipped items.": "สามารถล้วงกระเป๋าสิ่งของที่ติดตั้งได้",
    "Buying and selling prices are 10% better.": "ราคาซื้อและขายดีขึ้น 10%",
    "Buying and selling prices are 15% better.": "ราคาซื้อและขายดีขึ้น 15%",
    "Buying and selling prices are 20% better.": "ราคาซื้อและขายดีขึ้น 20%",
    "Buying and selling prices are 25% better.": "ราคาซื้อและขายดีขึ้น 25%",
    "Buying and selling prices are 30% better.": "ราคาซื้อและขายดีขึ้น 30%",
    "10% better prices with the opposite sex.": "ราคาดีขึ้น 10% สำหรับเพศตรงข้าม",
    "Can bribe guards to ignore crimes.": "สามารถติดสินบนผู้คุมเพื่อเพิกเฉยต่ออาชญากรรมได้",
    "Persuasion attempts are 30% easier.": "ความพยายามโน้มน้าวใจง่ายขึ้น 30%",
    "Intimidation is twice as successful.": "การข่มขู่ประสบความสำเร็จเป็นสองเท่า",
    "Can sell any type of item to any kind of merchant.": "สามารถขายสินค้าประเภทใดก็ได้ให้กับผู้ค้าทุกประเภท",
    "Can invest 500 gold with a shopkeeper to increase his available gold permanently.": "สามารถลงทุน 500 ทองกับเจ้าของร้านเพื่อเพิ่มทองที่มีอยู่อย่างถาวร",
    "Can barter stolen goods with any merchant you have invested in.": "สามารถแลกเปลี่ยนสินค้าที่ถูกขโมยกับร้านค้าที่คุณลงทุนได้",
    "Every merchant in the world gains 1000 gold for bartering.": "พ่อค้าทุกคนในโลกจะได้รับ 1,000 ทองจากการแลกเปลี่ยน"
};
//# sourceMappingURL=descriptions-th.js.map