// Thai translations for perk descriptions.
export const thaiDescriptions: Record<string, string> = {
  "Potions and poisons you make are 20% stronger.": "Potion และ Poison ที่สร้างแรงขึ้น 20%",
  "Potions and poisons you make are 40% stronger.": "Potion และ Poison ที่สร้างแรงขึ้น 40%",
  "Potions and poisons you make are 60% stronger.": "Potion และ Poison ที่สร้างแรงขึ้น 60%",
  "Potions and poisons you make are 80% stronger.": "Potion และ Poison ที่สร้างแรงขึ้น 80%",
  "Potions and poisons you make are 100% stronger.": "Potion และ Poison ที่สร้างแรงขึ้น 100%",
  "Potions you mix that restore Health, Magicka or Stamina are 25% more powerful.": "ยาที่คุณผสมเพื่อฟื้นฟูสุขภาพ Magicka หรือ Stamina จะมีพลังมากขึ้น 25%",
  "Poisons you mix are 25% more effective.": "พิษที่คุณผสมจะมีประสิทธิภาพมากขึ้น 25%",
  "Potions you mix with beneficial effects have an additional 25% greater magnitude.": "Potion ที่สร้างซึ่งมีผลดีมีความแรงเพิ่มอีก 25%",
  "Poisins applied to weapons last for twice as many hits.": "Poison ที่ทาอาวุธมีผลต่อจำนวนครั้งที่โจมตีเป็น 2 เท่า",
  "Eating an ingredient reveals first two effects.": "กิน Ingredient แล้วเห็น 2 Effects แรก",
  "Eating an ingredient reveals first three effects.": "กิน Ingredient แล้วเห็น 3 Effects แรก",
  "Eating an ingredient reveals first four effects.": "กิน Ingredient แล้วเห็น 4 Effects แรก",
  "Two ingredients are gathered from plants.": "เก็บ Ingredient จากพืชได้ 2 ชิ้นแทน 1 ชิ้น",
  "50% resistance to all poisons.": "ต้านทานพิษทั้งหมด 50%",
  "All negative effects are removed from created potions, and all positive effects are removed from created poisons.": "ผลกระทบเชิงลบทั้งหมดจะถูกลบออกจากยาที่สร้างขึ้น และผลกระทบเชิงบวกทั้งหมดจะถูกลบออกจากยาพิษที่สร้างขึ้น",
  "Cast Novice level Illusion spells for half magicka.": "ร่ายเวทย์มนตร์ระดับเริ่มต้นใช้เวทมนตร์เพียงครึ่งเดียว",
  "Dual casting an Illusion spell overcharges the effects into an even more powerful version.": "การใช้เวทย์มนตร์ Illusion แบบคู่จะชาร์จเอฟเฟกต์มากเกินไปจนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
  "Cast Apprentice level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
  "Calm spells now work on higher level opponents. Cumulative with Kindred Mage and Animage.": "เวท Calm มีผลกับศัตรู Level สูงขึ้น ผลรวมกับ Kindred Mage และ Animage",
  "Illusion spells now work on higher level animals.": "คาถาภาพลวงตาตอนนี้ใช้ได้กับสัตว์ที่มีเลเวลสูงกว่าแล้ว",
  "Cast Adept level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Expert level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Master level Illusion spells for half magicka.": "ร่ายคาถาสายภาพลวงตาระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
  "Fear spells work on higher level opponents. Cumulative with Kindred Mage and Animage.": "เวท Fear มีผลกับศัตรู Level สูงขึ้น ผลรวมกับ Kindred Mage และ Animage",
  "Frenzy spells work on higher level opponents. Cumulative with Kindred Mage and Animage.": "เวท Frenzy มีผลกับศัตรู Level สูงขึ้น ผลรวมกับ Kindred Mage และ Animage",
  "All Illusion spells work on higher level people.": "คาถาภาพลวงตาทั้งหมดใช้ได้กับผู้คนที่มีระดับสูงกว่า",
  "All spells you cast from any school of magic are silent to others.": "คาถาทั้งหมดที่คุณร่ายจากโรงเรียนเวทมนตร์แห่งใดก็ตามจะไม่ส่งเสียงต่อผู้อื่น",
  "Illusion spells work on undead, daedra and automatons.": "คาถาภาพลวงตาใช้ได้กับอันเดด เดดรา และออโตเมตอน",
  "Cast Novice level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Novice ใช้ Magicka เพียงครึ่งเดียว",
  "Can summon atronachs or raise undead twice as far away.": "ร่ายเวทอัญเชิญ Atronach หรือชุบชีวิต Undead ได้ไกลขึ้น 2 เท่า",
  "Can summon atronachs or raise undead three times as far away.": "ร่ายเวทอัญเชิญ Atronach หรือชุบชีวิต Undead ได้ไกลขึ้น 3 เท่า",
  "Dual casting a Conjuration spell overcharges the spell, allowing it to last longer.": "การร่ายเวทย์มนตร์แบบคู่จะชาร์จพลังเวทย์มากเกินไป และทำให้คงอยู่ได้นานขึ้น",
  "Greater duration for reanimated undead.": "ระยะเวลาที่มากขึ้นสำหรับอันเดดที่ฟื้นคืนชีพ",
  "Bound weapons do more damage.": "อาวุธ Bound สร้างความเสียหายเพิ่มขึ้น",
  "Cast Apprentice level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
  "Double duration for conjured Atronachs.": "ระยะเวลาสองเท่าสำหรับ Atronach ที่เสก",
  "Conjured Atronachs are 50% more powerful.": "Atronachs ที่เสกจะมีพลังมากขึ้น 50%",
  "Reanimated undead have 100 points more health.": "Undead ที่ฟื้นคืนชีพจะมีสุขภาพเพิ่มขึ้น 100 แต้ม",
  "You can have two atronachs or reanimated zombies.": "คุณสามารถมี atronach สองตัวหรือซอมบี้ที่ฟื้นคืนชีพได้",
  "Bound weapons cast Soul Trap on targets.": "อาวุธ Bound ร่าย Soul Trap ใส่เป้าหมาย",
  "Bound weapons will banish summoned creatures and turn raised ones.": "อาวุธ Bound ขับไล่สิ่งอัญเชิญและทำให้ Undead ที่ถูกชุบชีวิตหนีไป",
  "Cast Adept level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Expert level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Master level Conjuration spells for half magicka.": "ร่ายคาถาสายอัญเชิญระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Novice level Destruction spells for half magicka.": "คาถาทำลายล้างระดับเริ่มต้นใช้เวทมนตร์เพียงครึ่งเดียว",
  "Dual casting a Destruction spell overcharges the effects into an even more powerful version.": "การร่ายเวทย์ทำลายล้างแบบคู่จะอัดพลังเอฟเฟกต์มากเกินไปจนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
  "Most destruction spells will stagger an opponent when dual cast.": "คาถาทำลายล้างส่วนใหญ่จะทำให้คู่ต่อสู้เดินโซเซเมื่อร่ายแบบคู่",
  "Fire spells do 25% more damage.": "เวทไฟสร้างความเสียหายเพิ่ม 25%",
  "Fire spells do 50% more damage.": "เวทไฟสร้างความเสียหายเพิ่ม 50%",
  "Fire damage causes targets to flee if their health is low.": "ความเสียหายจากไฟจะทำให้เป้าหมายหลบหนีหากพลังชีวิตต่ำ",
  "Frost spells do 25% more damage.": "เวทน้ำแข็งสร้างความเสียหายเพิ่ม 25%",
  "Frost spells do 50% more damage.": "เวทน้ำแข็งสร้างความเสียหายเพิ่ม 50%",
  "Frost damage paralyzes targets if their health is low.": "ความเสียหายจากน้ำแข็งจะทำให้เป้าหมายเป็นอัมพาตหากพลังชีวิตของพวกเขาต่ำ",
  "Shock spells do 25% more damage.": "เวทสายฟ้าสร้างความเสียหายเพิ่ม 25%",
  "Shock spells do 50% more damage.": "เวทสายฟ้าสร้างความเสียหายเพิ่ม 50%",
  "Shock damage disintegrates targets if their health is low.": "ความเสียหายจากช็อตจะสลายเป้าหมายหากพลังชีวิตของพวกเขาต่ำ",
  "Cast Apprentice level Destruction spells for half magicka.": "ร่ายคาถาสายทำลายล้างระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
  "Can place runes five times farther away.": "สามารถวาง Rune ได้ไกลขึ้น 5 เท่า",
  "Cast Adept level Destruction spells for half magicka.": "ร่ายคาถาสายทำลายล้างระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Expert level Destruction spells for half magicka.": "ร่ายคาถาทำลายล้างระดับผู้เชี่ยวชาญใช้เวทมนตร์เพียงครึ่งเดียว",
  "Cast Master level Destruction spells for half magicka.": "คาถาทำลายล้างระดับปรมาจารย์ใช้เวทมนตร์เพียงครึ่งเดียว",
  "Cast Novice level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Novice ใช้ Magicka เพียงครึ่งเดียว",
  "Healing spells also restore Stamina.": "คาถารักษายังช่วยฟื้นฟูความแข็งแกร่งอีกด้วย",
  "Healing spells cure 50% more.": "คาถารักษารักษาได้มากขึ้น 50%",
  "All spells are more effective against undead.": "คาถาทั้งหมดมีประสิทธิภาพมากกว่ากับอันเดด",
  "Wards recharge your magicka when hit with spells.": "วอร์ดจะชาร์จเวทย์มนตร์ของคุณเมื่อถูกโจมตีด้วยคาถา",
  "Cast Apprentice level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Adept level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Expert level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
  "Cast Master level Restoration spells for half magicka.": "ร่ายคาถาสายฟื้นฟูระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
  "Magicka regenerates 25% faster.": "Magicka ฟื้นเร็วขึ้น 25%",
  "Magicka regenerates 50% faster.": "Magicka ฟื้นเร็วขึ้น 50%",
  "Once a day, heals 250 points automatically if you fall below 10% health.": "วันละครั้ง จะรักษา 250 แต้มโดยอัตโนมัติหากคุณมีพลังชีวิตต่ำกว่า 10%",
  "Dual casting a Restoration spell overcharges the effects into an even more powerful version.": "การร่ายเวทย์มนตร์การฟื้นฟูแบบคู่จะชาร์จเอฟเฟกต์มากเกินไปจนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
  "Cast Novice level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Novice ใช้ Magicka เพียงครึ่งเดียว",
  "Dual casting an Alteration spell overcharges the effects into an even more powerful version.": "การร่ายเวทย์มนตร์ Alteration แบบคู่จะเพิ่มพลังให้กับเอฟเฟกต์จนกลายเป็นเวอร์ชันที่ทรงพลังยิ่งขึ้น",
  "Cast Apprentice level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Apprentice ใช้ Magicka เพียงครึ่งเดียว",
  "Protection spells like Stoneflesh are twice as strong if not wearing armor.": "เวทป้องกัน เช่น Stoneflesh มีประสิทธิภาพเป็น 2 เท่าเมื่อไม่สวมเกราะ",
  "Protection spells like Stoneflesh are 2.5 times as strong if not wearing armor.": "เวทป้องกัน เช่น Stoneflesh มีประสิทธิภาพเป็น 2.5 เท่าเมื่อไม่สวมเกราะ",
  "Protection spells like Stoneflesh are three times as strong if not wearing armor.": "เวทป้องกัน เช่น Stoneflesh มีประสิทธิภาพเป็น 3 เท่าเมื่อไม่สวมเกราะ",
  "Blocks 10% of a spell's effects.": "ต้านทานผลของเวท 10%",
  "Blocks 20% of a spell's effects.": "ต้านทานผลของเวท 20%",
  "Blocks 30% of a spell's effects.": "ต้านทานผลของเวท 30%",
  "Cast Adept level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Adept ใช้ Magicka เพียงครึ่งเดียว",
  "Alteration spells have 50% greater duration.": "เวท Alteration มีระยะเวลานานขึ้น 50%",
  "Cast Expert level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Expert ใช้ Magicka เพียงครึ่งเดียว",
  "Absorb 30% of the magicka of any spells that hit you.": "ดูดซับเวทย์มนตร์ 30% ของคาถาที่โจมตีคุณ",
  "Cast Master level Alteration spells for half magicka.": "ร่ายคาถาสายดัดแปลงระดับ Master ใช้ Magicka เพียงครึ่งเดียว",
  "New enchantments are 20% stronger.": "Enchantment ที่สร้างใหม่แรงขึ้น 20%",
  "New enchantments are 40% stronger.": "Enchantment ที่สร้างใหม่แรงขึ้น 40%",
  "New enchantments are 60% stronger.": "Enchantment ที่สร้างใหม่แรงขึ้น 60%",
  "New enchantments are 80% stronger.": "Enchantment ที่สร้างใหม่แรงขึ้น 80%",
  "New enchantments are 100% stronger.": "Enchantment ที่สร้างใหม่แรงขึ้น 100%",
  "Fire enchantments on weapons and armor are 25% stronger.": "มนต์เสน่ห์ไฟบนอาวุธและชุดเกราะนั้นแข็งแกร่งขึ้น 25%",
  "Skill enchantments on armor are 25% stronger.": "ทักษะการร่ายมนตร์บนชุดเกราะนั้นแข็งแกร่งขึ้น 25%",
  "Soul gems provide extra magicka for recharging.": "Soul gems มอบเวทย์มนตร์พิเศษสำหรับการชาร์จใหม่",
  "Death blows to creatures, but not people, trap 5% of the victim's soul, recharging the weapon.": "เมื่อสังหารสิ่งมีชีวิตที่ไม่ใช่มนุษย์ด้วยอาวุธ จะดูดซับ 5% ของ Soul เป้าหมายเพื่อเติม Charge ให้อาวุธ",
  "Frost enchantments on weapons and armor are 25% stronger.": "มนต์เสน่ห์ฟรอสต์บนอาวุธและชุดเกราะนั้นแข็งแกร่งขึ้น 25%",
  "Shock enchantments on weapons and armor are 25% stronger.": "มนต์เสน่ห์สายสายฟ้าบนอาวุธและชุดเกราะมีประสิทธิภาพเพิ่มขึ้น 25%",
  "Health, magicka, and stamina enchantments on armor are 25% stronger.": "พลังชีวิต เวทมนตร์ และความแข็งแกร่งบนชุดเกราะแข็งแกร่งขึ้น 25%",
  "Can put two enchantments on the same item.": "สามารถใส่มนต์เสน่ห์ได้ 2 อย่างในรายการเดียวกัน",
  "Can create Steel armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Steel ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Elven armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Elven ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "You can improve magical weapons and armor.": "คุณสามารถปรับปรุงอาวุธและชุดเกราะเวทย์มนตร์ได้",
  "Can create Dwarven armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Dwarven ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Scaled and Plate armor at forges, and improve them twice as much.": "สามารถสร้างเกราะ Scaled และ Steel Plate ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Glass armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Glass ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Orcish armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Orcish ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Ebony armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Ebony ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Daedric armor and weapons at forges, and improve them twice as much.": "สามารถสร้างอาวุธและเกราะ Daedric ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Can create Dragon armor at forges, and improve them twice as much.": "สามารถสร้าง Dragon Armor ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Increases armor rating for Heavy Armor by 20%.": "Armor Rating ของ Heavy Armor เพิ่ม 20%",
  "Increases armor rating for Heavy Armor by 40%.": "Armor Rating ของ Heavy Armor เพิ่ม 40%",
  "Increases armor rating for Heavy Armor by 60%.": "Armor Rating ของ Heavy Armor เพิ่ม 60%",
  "Increases armor rating for Heavy Armor by 80%.": "Armor Rating ของ Heavy Armor เพิ่ม 80%",
  "Increases armor rating for Heavy Armor by 100%.": "Armor Rating ของ Heavy Armor เพิ่ม 100%",
  "Unarmed attacks with Heavy Armor gauntlets do their armor rating in extra damage.": "การโจมตีมือเปล่าสร้าง Damage เพิ่มเท่ากับ Armor Rating ของถุงมือ Heavy Armor ที่สวม",
  "Half damage from falling if wearing all Heavy Armor: head, chest, hands, feet.": "ได้รับความเสียหายจากการตกจากที่สูงลดลง 50% เมื่อสวม Heavy Armor ครบชุด: ศีรษะ, ลำตัว, มือ และเท้า",
  "Heavy Armor weighs nothing and doesn't slow you down when worn.": "Heavy Armor ไม่มีน้ำหนักและไม่ทำให้คุณช้าลงเมื่อสวมใส่",
  "25% Armor bonus if wearing all Heavy Armor: head, chest, hands, feet.": "โบนัสเกราะ 25% หากสวมเกราะหนักทั้งหมด: หัว, หน้าอก, มือ, เท้า",
  "50% less stagger when wearing only Heavy Armor.": "ลดการถูก Stagger 50% เมื่อสวมเฉพาะ Heavy Armor",
  "Additional 25% Armor bonus if wearing a matched set of Heavy Armor.": "Armor เพิ่มอีก 25% เมื่อใส่ Heavy Armor เป็นชุดเดียวกัน",
  "10% chance to reflect melee damage back to the enemy while wearing all Heavy Armor: head, chest, hands, feet.": "มีโอกาส 10% ที่จะสะท้อนความเสียหายระยะประชิดกลับไปยังศัตรูขณะสวมเกราะหนักทั้งหมด: หัว, หน้าอก, มือ, เท้า",
  "Blocking is 20% more effective.": "การ Block มีประสิทธิภาพเพิ่ม 20%",
  "Blocking is 25% more effective.": "การ Block มีประสิทธิภาพเพิ่ม 25%",
  "Blocking is 30% more effective.": "การ Block มีประสิทธิภาพเพิ่ม 30%",
  "Blocking is 35% more effective.": "การ Block มีประสิทธิภาพเพิ่ม 35%",
  "Blocking is 40% more effective.": "การ Block มีประสิทธิภาพเพิ่ม 40%",
  "Arrows that hit the shield do no damage.": "ลูกศรที่โดนโล่จะไม่สร้างความเสียหาย",
  "Time slows down if you are blocking during an enemy's power attack.": "เวลาจะช้าลงหากคุณกำลังบล็อคในระหว่างการโจมตีด้วยพลังของศัตรู",
  "Able to do a power bash.": "สามารถทำการทุบตีพลังได้",
  "Blocking with a shield reduces incoming fire, frost, and shock damage by 50%.": "Block ด้วย Shield ลด Fire, Frost และ Shock Damage 50%",
  "Able to move faster with a shield raised.": "สามารถเคลื่อนที่ได้เร็วขึ้นด้วยการยกโล่ขึ้น",
  "Bashing does five times more damage.": "Bash สร้างความเสียหายเป็น 5 เท่า",
  "Chance to disarm when power bashing.": "Power Bash มีโอกาสปลดอาวุธศัตรู",
  "Sprinting with a shield raised knocks down most targets.": "การวิ่งด้วยโล่ที่ยกขึ้นจะทำให้เป้าหมายส่วนใหญ่ล้มลง",
  "Two-Handed weapons do 20% more damage.": "อาวุธ Two-Handed สร้างความเสียหายเพิ่ม 20%",
  "Two-Handed weapons do 40% more damage.": "อาวุธ Two-Handed สร้างความเสียหายเพิ่ม 40%",
  "Two-Handed weapons do 60% more damage.": "อาวุธ Two-Handed สร้างความเสียหายเพิ่ม 60%",
  "Two-Handed weapons do 80% more damage.": "อาวุธ Two-Handed สร้างความเสียหายเพิ่ม 80%",
  "Two-Handed weapons do 100% more damage.": "อาวุธ Two-Handed สร้างความเสียหายเพิ่ม 100%",
  "Attacks with battle axes cause extra bleeding damage.": "Battleaxe ทำ Bleeding Damage เพิ่มขึ้น",
  "Power attacks with two-handed weapons cost 25% less stamina.": "การโจมตีด้วยพลังด้วยอาวุธสองมือใช้ค่าความแข็งแกร่งลดลง 25%",
  "Attacks with greatsword have a 10% chance of doing critical damage.": "Greatsword มีโอกาส 10% สร้าง Critical Damage",
  "Attacks with greatsword have a 15% chance of doing critical damage.": "Greatsword มีโอกาส 15% สร้าง Critical Damage",
  "Attacks with greatsword have a 20% chance of doing critical damage.": "Greatsword มีโอกาส 20% สร้าง Critical Damage",
  "Attacks with warhammers ignore 25% of armor.": "การโจมตีด้วย Warhammer ไม่คิด Armor ของเป้าหมาย 25%",
  "Attacks with warhammers ignore 50% of armor.": "การโจมตีด้วย Warhammer ไม่คิด Armor ของเป้าหมาย 50%",
  "Attacks with warhammers ignore 75% of armor.": "การโจมตีด้วย Warhammer ไม่คิด Armor ของเป้าหมาย 75%",
  "Can do a two-handed power attack while sprinting that does double critical damage.": "สามารถโจมตีด้วยพลังสองมือขณะวิ่งซึ่งสร้างความเสียหายคริติคอลเป็นสองเท่า",
  "Standing power attacks do 25% bonus damage with a chance to decapitate your enemies.": "การโจมตีด้วยพลังยืนจะสร้างโบนัสความเสียหาย 25% พร้อมโอกาสในการตัดหัวศัตรูของคุณ",
  "Sideways power attacks with two-handed weapons hit all targets in front of you.": "โจมตีด้วยอาวุธสองมือด้านข้างโจมตีทุกเป้าหมายที่อยู่ตรงหน้าคุณ",
  "Backwards power attack has a 25% chance to paralyze the target.": "การโจมตีด้วยพลังถอยหลังมีโอกาส 25% ที่จะทำให้เป้าหมายเป็นอัมพาต",
  "One-Handed weapons do 20% more damage.": "อาวุธ One-Handed สร้างความเสียหายเพิ่ม 20%",
  "One-Handed weapons do 40% more damage.": "อาวุธ One-Handed สร้างความเสียหายเพิ่ม 40%",
  "One-Handed weapons do 60% more damage.": "อาวุธ One-Handed สร้างความเสียหายเพิ่ม 60%",
  "One-Handed weapons do 80% more damage.": "อาวุธ One-Handed สร้างความเสียหายเพิ่ม 80%",
  "One-Handed weapons do 100% more damage.": "อาวุธ One-Handed สร้างความเสียหายเพิ่ม 100%",
  "Attacks with war axes cause extra bleeding damage.": "War Axe ทำ Bleeding Damage เพิ่มขึ้น",
  "Power attacks with one-handed-weapons cost 25% less stamina.": "การโจมตีด้วยพลังด้วยอาวุธมือเดียวจะใช้ค่าความแข็งแกร่งลดลง 25%",
  "Attacks with maces ignore 25% of armor.": "การโจมตีด้วย Mace ไม่คิด Armor ของเป้าหมาย 25%",
  "Attacks with maces ignore 50% of armor.": "การโจมตีด้วย Mace ไม่คิด Armor ของเป้าหมาย 50%",
  "Attacks with maces ignore 75% of armor.": "การโจมตีด้วย Mace ไม่คิด Armor ของเป้าหมาย 75%",
  "Attacks with swords have a 10% chance of doing critical damage.": "Sword มีโอกาส 10% สร้าง Critical Damage",
  "Attacks with swords have a 15% chance of doing critical damage.": "Sword มีโอกาส 15% สร้าง Critical Damage",
  "Attacks with swords have a 20% chance of doing critical damage.": "Sword มีโอกาส 20% สร้าง Critical Damage",
  "Dual wielding attacks are 20% faster.": "Dual-Wield โจมตีเร็วขึ้น 20%",
  "Dual wielding attacks are 35% faster.": "Dual-Wield โจมตีเร็วขึ้น 35%",
  "Dual wielding power attacks do 50% bonus damage.": "การโจมตีด้วยพลังอาวุธคู่จะสร้างความเสียหายโบนัส 50%",
  "Can do a one-handed power attack while sprinting that does double critical damage.": "สามารถโจมตีด้วยพลังด้วยมือเดียวขณะวิ่งซึ่งสร้างความเสียหายคริติคอลเป็นสองเท่า",
  "Bows do 20% more damage.": "ธนูสร้างความเสียหายเพิ่ม 20%",
  "Bows do 40% more damage.": "ธนูสร้างความเสียหายเพิ่ม 40%",
  "Bows do 60% more damage.": "ธนูสร้างความเสียหายเพิ่ม 60%",
  "Bows do 80% more damage.": "ธนูสร้างความเสียหายเพิ่ม 80%",
  "Bows do 100% more damage.": "ธนูสร้างความเสียหายเพิ่ม 100%",
  "Pressing Block while aiming will zoom in your view.": "การกดบล็อกขณะเล็งจะซูมมุมมองของคุณ",
  "10% chance of a critical hit that does extra damage.": "ธนูมีโอกาส 10% สร้าง Critical Damage เพิ่มเติม",
  "15% chance of a critical hit that does extra damage.": "ธนูมีโอกาส 15% สร้าง Critical Damage เพิ่มเติม",
  "20% chance of a critical hit that does extra damage.": "ธนูมีโอกาส 20% สร้าง Critical Damage เพิ่มเติม",
  "Zooming in with a bow slows time by 25%.": "ขณะ Zoom ด้วย Bow เวลาช้าลง 25%",
  "Zooming in with a bow slows time by 50%.": "ขณะ Zoom ด้วย Bow เวลาช้าลง 50%",
  "Arrows stagger all but the largest opponents 50% of the time.": "ลูกธนูมีโอกาส 50% ทำให้ศัตรูทุกขนาด ยกเว้นตัวที่ใหญ่ที่สุด เสียหลัก",
  "Can draw a bow 30% faster.": "สามารถชักธนูได้เร็วขึ้น 30%",
  "Recover twice as many arrows from dead bodies.": "เก็บลูกธนูคืนจากศพได้ 2 เท่า",
  "Able to move faster with a drawn bow.": "สามารถเคลื่อนที่ได้เร็วขึ้นด้วยธนูที่ชักออกมา",
  "15% chance of paralyzing the target for a few seconds.": "มีโอกาส 15% ที่จะทำให้เป้าหมายเป็นอัมพาตเป็นเวลาไม่กี่วินาที",
  "Increase armor rating for Light armor by 20%.": "Armor Rating ของ Light Armor เพิ่ม 20%",
  "Increase armor rating for Light armor by 40%.": "Armor Rating ของ Light Armor เพิ่ม 40%",
  "Increase armor rating for Light armor by 60%.": "Armor Rating ของ Light Armor เพิ่ม 60%",
  "Increase armor rating for Light armor by 80%.": "Armor Rating ของ Light Armor เพิ่ม 80%",
  "Increase armor rating for Light armor by 100%.": "Armor Rating ของ Light Armor เพิ่ม 100%",
  "25% Armor bonus if wearing all Light Armor: head, chest, hands, feet.": "โบนัสเกราะ 25% หากสวมเกราะเบาทั้งหมด: หัว, หน้าอก, มือ, เท้า",
  "Light Armor weighs nothing and doesn't slow you down when worn.": "Light Armor ไม่มีน้ำหนักและไม่ทำให้คุณช้าลงเมื่อสวมใส่",
  "Additional 25% Armor bonus if wearing a matched set of Light Armor.": "Armor เพิ่มอีก 25% เมื่อใส่ Light Armor เป็นชุดเดียวกัน",
  "Stamina regenerates 50% faster in all Light Armor: head, chest, hands, feet.": "ความแข็งแกร่งจะฟื้นฟูเร็วขึ้น 50% ในชุดเกราะเบาทั้งหมด: หัว, หน้าอก, มือ, เท้า",
  "10% chance of avoiding all damage from a melee attack while wearing all Light Armor: head, chest, hands, feet.": "มีโอกาส 10% ที่จะหลีกเลี่ยงความเสียหายทั้งหมดจากการโจมตีระยะประชิดขณะสวมเกราะเบาทั้งหมด: หัว, หน้าอก, มือ, เท้า",
  "You are 20% harder to detect when sneaking.": "ตรวจจับคุณยากขึ้น 20% ขณะ Sneak",
  "You are 25% harder to detect when sneaking.": "ตรวจจับคุณยากขึ้น 25% ขณะ Sneak",
  "You are 30% harder to detect when sneaking.": "ตรวจจับคุณยากขึ้น 30% ขณะ Sneak",
  "You are 35% harder to detect when sneaking.": "ตรวจจับคุณยากขึ้น 35% ขณะ Sneak",
  "You are 40% harder to detect when sneaking.": "ตรวจจับคุณยากขึ้น 40% ขณะ Sneak",
  "Sneak attacks with one-handed weapons now do six times damage.": "การแอบโจมตีด้วยอาวุธมือเดียวจะสร้างความเสียหายได้หกเท่า",
  "Sneak attacks with bows now do three times damage.": "การโจมตีแบบลอบโจมตีด้วยธนูจะสร้างความเสียหายได้ 3 เท่า",
  "Sneak attacks with daggers now do a total of fifteen times normal damage.": "การโจมตีด้วยมีดสั้นตอนนี้จะสร้างความเสียหายรวม 15 เท่าของความเสียหายปกติ",
  "Noise from armor is reduced 50%.": "เสียงจากเกราะลดลง 50%",
  "You won't trigger pressure plates.": "คุณจะไม่เรียกใช้แผ่นแรงดัน",
  "Sprinting while sneaking executes a silent forward roll.": "วิ่งขณะลอบเร้นเพื่อกลิ้งตัวไปข้างหน้าอย่างเงียบเชียบ",
  "Walking and running does not affect detection.": "การเดินและวิ่งไม่ส่งผลต่อการตรวจจับ",
  "Crouching stops combat for a moment and forces distant opponents to search for a target.": "การหมอบหยุดการต่อสู้ชั่วขณะและบังคับให้คู่ต่อสู้ที่อยู่ห่างไกลค้นหาเป้าหมาย",
  "Novice locks are much easier to pick.": "สะเดาะกุญแจระดับ Novice ได้ง่ายขึ้นมาก",
  "Apprentice locks are much easier to pick.": "สะเดาะกุญแจระดับ Apprentice ได้ง่ายขึ้นมาก",
  "Able to pick locks without being noticed.": "สะเดาะกุญแจได้โดยไม่ถูกสังเกต",
  "Automatically gives you a copy of a picked lock's key if it has one.": "เมื่อสะเดาะกุญแจสำเร็จ จะได้รับสำเนากุญแจของมันโดยอัตโนมัติหากมี",
  "Adept locks are much easier to pick.": "สะเดาะกุญแจระดับ Adept ได้ง่ายขึ้นมาก",
  "Find more gold in chests.": "ค้นหาทองคำเพิ่มเติมในหีบ",
  "50% greater chance of finding special treasure.": "โอกาสพบ Special Treasure เพิ่มขึ้น 50%",
  "Expert locks are much easier to pick.": "สะเดาะกุญแจระดับ Expert ได้ง่ายขึ้นมาก",
  "Pick starts close to the lock opening position.": "เริ่มหมุนสะเดาะกุญแจใกล้ตำแหน่งปลดล็อกมากขึ้น",
  "Lockpicks never break.": "สะเดาะกุญแจไม่หัก",
  "Master locks are much easier to pick.": "สะเดาะกุญแจระดับ Master ได้ง่ายขึ้นมาก",
  "Pickpocketing bonus of 20%. Item weight and value reduce pickpocketing odds.": "โบนัส Pickpocket 20% น้ำหนักและมูลค่าไอเทมลดโอกาสสำเร็จ",
  "Pickpocketing bonus of 40%. Item weight and value reduce pickpocketing odds.": "โบนัส Pickpocket 40% น้ำหนักและมูลค่าไอเทมลดโอกาสสำเร็จ",
  "Pickpocketing bonus of 60%. Item weight and value reduce pickpocketing odds.": "โบนัส Pickpocket 60% น้ำหนักและมูลค่าไอเทมลดโอกาสสำเร็จ",
  "Pickpocketing bonus of 80%. Item weight and value reduce pickpocketing odds.": "โบนัส Pickpocket 80% น้ำหนักและมูลค่าไอเทมลดโอกาสสำเร็จ",
  "Pickpocketing bonus of 100%. Item weight and value reduce pickpocketing odds.": "โบนัส Pickpocket 100% น้ำหนักและมูลค่าไอเทมลดโอกาสสำเร็จ",
  "+25% chance to pickpocket if the target is asleep.": "มีโอกาสล้วงกระเป๋า +25% หากเป้าหมายหลับอยู่",
  "Silently harm enemies by placing poisons in their pockets.": "ทำร้ายศัตรูอย่างเงียบๆ โดยการวางยาพิษไว้ในกระเป๋าของพวกมัน",
  "Pickpocketing gold is 50% easier.": "ล้วงกระเป๋าเหรียญทองได้ง่ายขึ้น 50%",
  "Carrying capacity is increased by 100.": "ความสามารถในการบรรทุกเพิ่มขึ้น 100",
  "Pickpocketing keys almost always works.": "ล้วงกระเป๋าเอากุญแจสำเร็จเกือบทุกครั้ง",
  "Can pickpocket equipped weapons.": "สามารถล้วงกระเป๋าอาวุธที่ติดตั้งได้",
  "Can pickpocket equipped items.": "สามารถล้วงกระเป๋าสิ่งของที่ติดตั้งได้",
  "Buying and selling prices are 10% better.": "ราคาซื้อขายดีขึ้น 10%",
  "Buying and selling prices are 15% better.": "ราคาซื้อขายดีขึ้น 15%",
  "Buying and selling prices are 20% better.": "ราคาซื้อขายดีขึ้น 20%",
  "Buying and selling prices are 25% better.": "ราคาซื้อขายดีขึ้น 25%",
  "Buying and selling prices are 30% better.": "ราคาซื้อขายดีขึ้น 30%",
  "10% better prices with the opposite sex.": "ราคาดีขึ้น 10% สำหรับเพศตรงข้าม",
  "Can bribe guards to ignore crimes.": "สามารถติดสินบนผู้คุมเพื่อเพิกเฉยต่ออาชญากรรมได้",
  "Persuasion attempts are 30% easier.": "ความพยายามโน้มน้าวใจง่ายขึ้น 30%",
  "Intimidation is twice as successful.": "Intimidation สำเร็จได้ดีขึ้น 2 เท่า",
  "Can sell any type of item to any kind of merchant.": "สามารถขายสินค้าประเภทใดก็ได้ให้กับผู้ค้าทุกประเภท",
  "Can invest 500 gold with a shopkeeper to increase his available gold permanently.": "สามารถลงทุน 500 ทองกับเจ้าของร้านเพื่อเพิ่มทองที่มีอยู่อย่างถาวร",
  "Can barter stolen goods with any merchant you have invested in.": "สามารถแลกเปลี่ยนสินค้าที่ถูกขโมยกับร้านค้าที่คุณลงทุนได้",
  "Every merchant in the world gains 1000 gold for bartering.": "พ่อค้าทุกคนในโลกจะได้รับ 1,000 ทองจากการแลกเปลี่ยน"
};
