// Generated from docs/skyrim_vanilla_perks_en_th.md.
export const perkDescriptionsTh: Record<string, string> = {
  "Novice Alteration": "เวท Alteration ระดับ Novice ใช้ Magicka ลดลง 50%",
  "Alteration Dual Casting": "ร่ายเวท Alteration สองมือเพื่อเพิ่มประสิทธิภาพของเวท",
  "Apprentice Alteration": "เวท Alteration ระดับ Apprentice ใช้ Magicka ลดลง 50%",
  "Mage Armor": "เวทป้องกัน เช่น Stoneflesh มีประสิทธิภาพเป็น 2 / 2.5 / 3 เท่าเมื่อไม่สวมเกราะ",
  "Magic Resistance": "เพิ่ม Magic Resistance 10% / 20% / 30%",
  "Adept Alteration": "เวท Alteration ระดับ Adept ใช้ Magicka ลดลง 50%",
  "Stability": "เวท Alteration มีระยะเวลานานขึ้น 50%",
  "Expert Alteration": "เวท Alteration ระดับ Expert ใช้ Magicka ลดลง 50%",
  "Atronach": "ดูดซับ Magicka 30% จากเวทศัตรูที่โจมตีโดนคุณ",
  "Master Alteration": "เวท Alteration ระดับ Master ใช้ Magicka ลดลง 50%",
  "Novice Conjuration": "เวท Conjuration ระดับ Novice ใช้ Magicka ลดลง 50%",
  "Conjuration Dual Casting": "ร่ายเวท Conjuration สองมือเพื่อเพิ่มระยะเวลาของเวท",
  "Mystic Binding": "อาวุธ Bound สร้างความเสียหายมากขึ้น",
  "Apprentice Conjuration": "เวท Conjuration ระดับ Apprentice ใช้ Magicka ลดลง 50%",
  "Soul Stealer": "อาวุธ Bound ใช้ Soul Trap กับเป้าหมาย",
  "Summoner": "ร่ายเวทอัญเชิญ Atronach หรือชุบชีวิต Undead ได้ไกลขึ้น 2 / 3 เท่า",
  "Necromancy": "Undead ที่ชุบชีวิตอยู่ได้นานขึ้น",
  "Atromancy": "Atronach ที่อัญเชิญอยู่ได้นานขึ้น 2 เท่า",
  "Adept Conjuration": "เวท Conjuration ระดับ Adept ใช้ Magicka ลดลง 50%",
  "Oblivion Binding": "อาวุธ Bound ขับไล่สิ่งอัญเชิญและทำให้ Undead ที่ถูกชุบชีวิตหนีไป",
  "Dark Souls": "Undead ที่ชุบชีวิตได้รับ Health เพิ่ม 100",
  "Expert Conjuration": "เวท Conjuration ระดับ Expert ใช้ Magicka ลดลง 50%",
  "Elemental Potency": "Atronach ที่อัญเชิญแข็งแกร่งขึ้น 50%",
  "Master Conjuration": "เวท Conjuration ระดับ Master ใช้ Magicka ลดลง 50%",
  "Twin Souls": "สามารถควบคุมสิ่งอัญเชิญหรือ Undead ที่ชุบชีวิตได้พร้อมกัน 2 ตัว",
  "Novice Destruction": "เวท Destruction ระดับ Novice ใช้ Magicka ลดลง 50%",
  "Destruction Dual Casting": "ร่ายเวท Destruction สองมือเพื่อเพิ่มพลังของเวท",
  "Apprentice Destruction": "เวท Destruction ระดับ Apprentice ใช้ Magicka ลดลง 50%",
  "Augmented Flames": "เวทไฟสร้างความเสียหายเพิ่ม 25% / 50%",
  "Augmented Frost": "เวทน้ำแข็งสร้างความเสียหายเพิ่ม 25% / 50%",
  "Augmented Shock": "เวทสายฟ้าสร้างความเสียหายเพิ่ม 25% / 50%",
  "Impact": "เวท Destruction ที่ร่ายสองมือส่วนใหญ่ทำให้ศัตรู Stagger",
  "Rune Master": "สามารถวาง Rune ได้ไกลขึ้น 5 เท่า",
  "Adept Destruction": "เวท Destruction ระดับ Adept ใช้ Magicka ลดลง 50%",
  "Intense Flames": "ความเสียหายไฟทำให้ศัตรูที่ Health ต่ำเกิด Fear และหนี",
  "Deep Freeze": "ความเสียหายน้ำแข็งสามารถทำให้ศัตรูที่ Health ต่ำ Paralyze",
  "Disintegrate": "ความเสียหายสายฟ้าสามารถ Disintegrate ศัตรูที่ Health ต่ำ",
  "Expert Destruction": "เวท Destruction ระดับ Expert ใช้ Magicka ลดลง 50%",
  "Master Destruction": "เวท Destruction ระดับ Master ใช้ Magicka ลดลง 50%",
  "Enchanter": "Enchantment ที่สร้างใหม่แรงขึ้น 20% / 40% / 60% / 80% / 100%",
  "Soul Squeezer": "Soul Gem เติม Charge ให้อาวุธเวทได้มากขึ้น",
  "Fire Enchanter": "Fire Enchantment แรงขึ้น 25%",
  "Soul Siphon": "เมื่อสังหารสิ่งมีชีวิตที่ไม่ใช่มนุษย์ด้วยอาวุธ จะดูดซับ 5% ของ Soul เป้าหมายเพื่อเติม Charge ให้อาวุธ",
  "Frost Enchanter": "Frost Enchantment แรงขึ้น 25%",
  "Insightful Enchanter": "Enchantment ประเภทเพิ่ม Skill บนเครื่องสวมใส่แรงขึ้น 25%",
  "Storm Enchanter": "Shock Enchantment แรงขึ้น 25%",
  "Corpus Enchanter": "Enchantment เพิ่ม Health, Magicka และ Stamina แรงขึ้น 25%",
  "Extra Effect": "สามารถใส่ Enchantment ได้ 2 อย่างในไอเทมเดียว",
  "Novice Illusion": "เวท Illusion ระดับ Novice ใช้ Magicka ลดลง 50%",
  "Illusion Dual Casting": "ร่ายเวท Illusion สองมือเพื่อเพิ่มพลังของเวท",
  "Animage": "เวท Illusion มีผลกับสัตว์ Level สูงขึ้น",
  "Apprentice Illusion": "เวท Illusion ระดับ Apprentice ใช้ Magicka ลดลง 50%",
  "Hypnotic Gaze": "เวท Calm มีผลกับศัตรู Level สูงขึ้น ผลรวมกับ Kindred Mage และ Animage",
  "Kindred Mage": "เวท Illusion มีผลกับมนุษย์ Level สูงขึ้น",
  "Adept Illusion": "เวท Illusion ระดับ Adept ใช้ Magicka ลดลง 50%",
  "Aspect of Terror": "เวท Fear มีผลกับศัตรู Level สูงขึ้น ผลรวมกับ Kindred Mage และ Animage",
  "Quiet Casting": "การร่ายเวททุก School เงียบและไม่ทำให้ผู้อื่นได้ยิน",
  "Rage": "เวท Frenzy มีผลกับศัตรู Level สูงขึ้น ผลรวมกับ Kindred Mage และ Animage",
  "Expert Illusion": "เวท Illusion ระดับ Expert ใช้ Magicka ลดลง 50%",
  "Master of the Mind": "เวท Illusion ใช้กับ Undead, Daedra และ Automatons ได้",
  "Master Illusion": "เวท Illusion ระดับ Master ใช้ Magicka ลดลง 50%",
  "Novice Restoration": "เวท Restoration ระดับ Novice ใช้ Magicka ลดลง 50%",
  "Restoration Dual Casting": "ร่ายเวท Restoration สองมือเพื่อเพิ่มพลังของเวท",
  "Regeneration": "เวทรักษาฟื้น Health เพิ่มขึ้น 50%",
  "Apprentice Restoration": "เวท Restoration ระดับ Apprentice ใช้ Magicka ลดลง 50%",
  "Recovery": "Magicka ฟื้นเร็วขึ้น 25% / 50%",
  "Respite": "เวทรักษาฟื้น Stamina ด้วย",
  "Adept Restoration": "เวท Restoration ระดับ Adept ใช้ Magicka ลดลง 50%",
  "Ward Absorb": "Ward ช่วยฟื้น Magicka เมื่อรับเวทโจมตี",
  "Necromage": "เวทมีประสิทธิภาพมากขึ้นเมื่อใช้กับ Undead",
  "Expert Restoration": "เวท Restoration ระดับ Expert ใช้ Magicka ลดลง 50%",
  "Avoid Death": "วันละครั้ง หาก Health ต่ำกว่า 10% จะฟื้น 250 Health อัตโนมัติ",
  "Master Restoration": "เวท Restoration ระดับ Master ใช้ Magicka ลดลง 50%",
  "Overdraw": "ธนูสร้างความเสียหายเพิ่ม 20% / 40% / 60% / 80% / 100%",
  "Eagle Eye": "กด Block ขณะเล็งเพื่อ Zoom",
  "Critical Shot": "ธนูมีโอกาส 10% / 15% / 20% สร้าง Critical Damage เพิ่มเติม",
  "Steady Hand": "ขณะ Zoom ด้วย Bow เวลาช้าลง 25% / 50%",
  "Power Shot": "ลูกธนูมีโอกาส 50% ทำให้ศัตรูส่วนใหญ่ Stagger",
  "Hunter's Discipline": "เก็บลูกธนูคืนจากศพได้ 2 เท่า",
  "Ranger": "เคลื่อนไหวเร็วขึ้นขณะง้างธนู",
  "Quick Shot": "ง้างธนูเร็วขึ้น 30%",
  "Bullseye": "ลูกธนูมีโอกาส 15% ทำให้เป้าหมาย Paralyze ชั่วคราว",
  "Shield Wall": "การ Block มีประสิทธิภาพเพิ่ม 20% / 25% / 30% / 35% / 40%",
  "Deflect Arrows": "ลูกธนูที่ชน Shield ไม่สร้างความเสียหาย",
  "Quick Reflexes": "เวลาช้าลงเมื่อ Block ขณะที่ศัตรูกำลังใช้ Power Attack",
  "Power Bash": "สามารถใช้ Power Bash ได้",
  "Elemental Protection": "Block ด้วย Shield ลด Fire, Frost และ Shock Damage 50%",
  "Deadly Bash": "Bash สร้างความเสียหายเป็น 5 เท่า",
  "Block Runner": "เคลื่อนไหวเร็วขึ้นขณะ Block ด้วย Shield หรืออาวุธ",
  "Disarming Bash": "Power Bash มีโอกาสปลดอาวุธศัตรู",
  "Shield Charge": "Sprint ขณะยก Shield สามารถชนศัตรูส่วนใหญ่ให้ล้ม",
  "Juggernaut": "Armor Rating ของ Heavy Armor เพิ่ม 20% / 40% / 60% / 80% / 100%",
  "Fists of Steel": "การโจมตีมือเปล่าสร้าง Damage เพิ่มเท่ากับ Armor Rating ของถุงมือ Heavy Armor ที่สวม",
  "Well Fitted": "Armor เพิ่ม 25% เมื่อใส่ Heavy Armor ครบ Head, Chest, Hands และ Feet",
  "Cushioned": "ลด Fall Damage ครึ่งหนึ่งเมื่อใส่ Heavy Armor ครบ",
  "Tower of Strength": "ลดการถูก Stagger 50% เมื่อสวมเฉพาะ Heavy Armor",
  "Conditioning": "Heavy Armor ที่สวมไม่มีน้ำหนักและไม่ลดความเร็วการเคลื่อนไหว",
  "Reflect Blows": "มีโอกาส 10% สะท้อน Melee Damage เมื่อใส่ Heavy Armor ครบ",
  "Armsman": "อาวุธ One-Handed สร้างความเสียหายเพิ่ม 20% / 40% / 60% / 80% / 100%",
  "Fighting Stance": "One-Handed Power Attack ใช้ Stamina ลดลง 25%",
  "Bladesman": "Sword มีโอกาส 10% / 15% / 20% สร้าง Critical Damage",
  "Bone Breaker": "การโจมตีด้วย Mace ไม่คิด Armor ของเป้าหมาย 25% / 50% / 75%",
  "Hack and Slash": "War Axe ทำ Bleeding Damage เพิ่มขึ้น",
  "Dual Flurry": "Dual-Wield โจมตีเร็วขึ้น 20% / 35%",
  "Savage Strike": "Standing Power Attack แรงขึ้น 25% และมีโอกาส Decapitate",
  "Critical Charge": "Sprinting Power Attack ทำ Double Critical Damage",
  "Dual Savagery": "Dual-Wield Power Attack สร้างความเสียหายเพิ่ม 50%",
  "Paralyzing Strike": "Backward Power Attack มีโอกาส 25% ทำให้ Paralyze",
  "Steel Smithing": "สามารถสร้างอาวุธและเกราะ Steel ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Elven Smithing": "สามารถสร้างอาวุธและเกราะ Elven ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Dwarven Smithing": "สามารถสร้างอาวุธและเกราะ Dwarven ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Advanced Armors": "สามารถสร้างเกราะ Scaled และ Steel Plate ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Orcish Smithing": "สามารถสร้างอาวุธและเกราะ Orcish ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Arcane Blacksmith": "สามารถ Improve อาวุธและเกราะที่มี Enchantment ได้",
  "Glass Smithing": "สามารถสร้างอาวุธและเกราะ Glass ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Ebony Smithing": "สามารถสร้างอาวุธและเกราะ Ebony ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Daedric Smithing": "สามารถสร้างอาวุธและเกราะ Daedric ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Dragon Armor": "สามารถสร้าง Dragon Armor ที่ Forge และ Improve ได้มากเป็น 2 เท่า",
  "Barbarian": "อาวุธ Two-Handed สร้างความเสียหายเพิ่ม 20% / 40% / 60% / 80% / 100%",
  "Champion's Stance": "Two-Handed Power Attack ใช้ Stamina ลดลง 25%",
  "Deep Wounds": "Greatsword มีโอกาส 10% / 15% / 20% สร้าง Critical Damage",
  "Limbsplitter": "Battleaxe ทำ Bleeding Damage เพิ่มขึ้น",
  "Skull Crusher": "การโจมตีด้วย Warhammer ไม่คิด Armor ของเป้าหมาย 25% / 50% / 75%",
  "Devastating Blow": "Standing Power Attack แรงขึ้น 25% และมีโอกาส Decapitate",
  "Great Critical Charge": "Sprinting Power Attack ทำ Double Critical Damage",
  "Sweep": "Sideways Power Attack โจมตีโดนศัตรูทั้งหมดด้านหน้า",
  "Warmaster": "Backward Power Attack มีโอกาส 25% ทำให้ Paralyze",
  "Alchemist": "Potion และ Poison ที่สร้างแรงขึ้น 20% / 40% / 60% / 80% / 100%",
  "Physician": "Potion ฟื้น Health, Magicka หรือ Stamina แรงขึ้น 25%",
  "Poisoner": "Poison ที่สร้างแรงขึ้น 25%",
  "Benefactor": "Potion ที่มีผลดีแรงขึ้น 25%",
  "Experimenter": "กิน Ingredient แล้วเห็น 2 / 3 / 4 Effects",
  "Concentrated Poison": "Poison ที่ทาอาวุธมีผล 2 ครั้ง",
  "Green Thumb": "เก็บ Ingredient จากพืชได้ 2 ชิ้นแทน 1 ชิ้น",
  "Snakeblood": "เพิ่ม Poison Resistance 50%",
  "Purity": "Potion ไม่มี Negative Effect และ Poison ไม่มี Positive Effect",
  "Agile Defender": "Armor Rating ของ Light Armor เพิ่ม 20% / 40% / 60% / 80% / 100%",
  "Custom Fit": "Armor เพิ่ม 25% เมื่อใส่ Light Armor ครบ Head, Chest, Hands และ Feet",
  "Unhindered": "Light Armor ที่สวมไม่มีน้ำหนักและไม่ลดความเร็วการเคลื่อนไหว",
  "Wind Walker": "Stamina ฟื้นเร็วขึ้น 50% เมื่อใส่ Light Armor ครบ",
  "Deft Movement": "มีโอกาส 10% หลบ Melee Damage ทั้งหมดเมื่อใส่ Light Armor ครบ",
  "Novice Locks": "Lock ระดับ Novice สะเดาะง่ายขึ้นมาก",
  "Apprentice Locks": "Lock ระดับ Apprentice สะเดาะง่ายขึ้นมาก",
  "Quick Hands": "สามารถสะเดาะกุญแจโดยคนอื่นไม่สังเกตเห็น",
  "Wax Key": "เมื่อสะเดาะ Lock ที่มี Key จะได้สำเนา Key อัตโนมัติ",
  "Adept Locks": "Lock ระดับ Adept สะเดาะง่ายขึ้นมาก",
  "Golden Touch": "พบ Gold ใน Chest มากขึ้น",
  "Treasure Hunter": "โอกาสพบ Special Treasure เพิ่มขึ้น 50%",
  "Expert Locks": "Lock ระดับ Expert สะเดาะง่ายขึ้นมาก",
  "Locksmith": "ตำแหน่งเริ่มต้นของ Lockpick อยู่ใกล้จุดเปิดมากขึ้น",
  "Unbreakable": "Lockpick ไม่แตก",
  "Master Locks": "Lock ระดับ Master สะเดาะง่ายขึ้นมาก",
  "Light Fingers": "โบนัส Pickpocket 20% / 40% / 60% / 80% / 100% น้ำหนักและมูลค่าไอเทมลดโอกาสสำเร็จ",
  "Night Thief": "Pickpocket เป้าหมายที่หลับง่ายขึ้น 25%",
  "Poisoned": "ใส่ Poison ในกระเป๋าศัตรูเพื่อทำร้ายแบบลอบเร้น",
  "Cutpurse": "ขโมย Gold ง่ายขึ้น 50%",
  "Extra Pockets": "Carry Weight เพิ่ม 100",
  "Keymaster": "Pickpocket Key สำเร็จแทบทุกครั้ง",
  "Misdirection": "ขโมยอาวุธที่เป้าหมายถืออยู่ได้ขณะ Sneak",
  "Perfect Touch": "ขโมยเสื้อผ้าหรือเกราะที่เป้าหมายสวมอยู่ได้ขณะ Sneak",
  "Stealth": "ตรวจจับคุณยากขึ้น 20% / 25% / 30% / 35% / 40% ขณะ Sneak",
  "Muffled Movement": "เสียงจาก Armor ลดลง 50%",
  "Backstab": "Sneak Attack ด้วย One-Handed Weapon ทำ Damage x6",
  "Light Foot": "ไม่ Trigger Pressure Plate",
  "Deadly Aim": "Sneak Attack ด้วย Bow ทำ Damage x3",
  "Silent Roll": "Sprint ขณะ Sneak จะทำ Silent Forward Roll",
  "Assassin's Blade": "Sneak Attack ด้วย Dagger ทำ Damage x15",
  "Silence": "การเดินและวิ่งไม่เพิ่มโอกาสถูกตรวจจับ",
  "Shadow Warrior": "Crouch ระหว่างต่อสู้ทำให้ศัตรูเสียการมองเห็นคุณชั่วขณะ",
  "Haggling": "ราคาซื้อขายดีขึ้น 10% / 15% / 20% / 25% / 30%",
  "Allure": "ราคาดีขึ้น 10% เมื่อซื้อขายกับเพศตรงข้าม",
  "Merchant": "สามารถขายไอเทมทุกประเภทให้ Merchant ทุกประเภท",
  "Investor": "ลงทุน 500 Gold กับร้านเพื่อเพิ่มเงินทุนของร้านแบบถาวร",
  "Fence": "สามารถขายของขโมยให้ Merchant ที่คุณเคยลงทุนได้",
  "Master Trader": "Merchant ทุกคนมี Gold สำหรับซื้อขายเพิ่ม 1,000",
  "Bribery": "สามารถติดสินบน Guard เพื่อให้มองข้าม Crime",
  "Persuasion": "Persuasion สำเร็จง่ายขึ้น 30%",
  "Intimidation": "Intimidation สำเร็จได้ดีขึ้น 2 เท่า"
};
